# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rj4/Qt/Tools/CMake/bin/cmake

# The command to remove a file.
RM = /home/rj4/Qt/Tools/CMake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rj4/untitledexmp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rj4/build-untitledexmp-Qt6-Release

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/rj4/Qt/Tools/CMake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/rj4/Qt/Tools/CMake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rj4/build-untitledexmp-Qt6-Release/CMakeFiles /home/rj4/build-untitledexmp-Qt6-Release//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rj4/build-untitledexmp-Qt6-Release/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitledexmp

# Build rule for target.
untitledexmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 untitledexmp
.PHONY : untitledexmp

# fast build rule for target.
untitledexmp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/build
.PHONY : untitledexmp/fast

#=============================================================================
# Target rules for targets named untitledexmp_autogen

# Build rule for target.
untitledexmp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 untitledexmp_autogen
.PHONY : untitledexmp_autogen

# fast build rule for target.
untitledexmp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp_autogen.dir/build.make CMakeFiles/untitledexmp_autogen.dir/build
.PHONY : untitledexmp_autogen/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

untitledexmp_autogen/mocs_compilation.o: untitledexmp_autogen/mocs_compilation.cpp.o
.PHONY : untitledexmp_autogen/mocs_compilation.o

# target to build an object file
untitledexmp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/untitledexmp_autogen/mocs_compilation.cpp.o
.PHONY : untitledexmp_autogen/mocs_compilation.cpp.o

untitledexmp_autogen/mocs_compilation.i: untitledexmp_autogen/mocs_compilation.cpp.i
.PHONY : untitledexmp_autogen/mocs_compilation.i

# target to preprocess a source file
untitledexmp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/untitledexmp_autogen/mocs_compilation.cpp.i
.PHONY : untitledexmp_autogen/mocs_compilation.cpp.i

untitledexmp_autogen/mocs_compilation.s: untitledexmp_autogen/mocs_compilation.cpp.s
.PHONY : untitledexmp_autogen/mocs_compilation.s

# target to generate assembly for a file
untitledexmp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitledexmp.dir/build.make CMakeFiles/untitledexmp.dir/untitledexmp_autogen/mocs_compilation.cpp.s
.PHONY : untitledexmp_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... untitledexmp_autogen"
	@echo "... untitledexmp"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... untitledexmp_autogen/mocs_compilation.o"
	@echo "... untitledexmp_autogen/mocs_compilation.i"
	@echo "... untitledexmp_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

